#version 330 core
out vec4 FragColor;

in vec3 ourColor;
in vec2 TexCoord;

// A sampler is auto-generated by OpenGL and is used to sample the texture (extract colors from it)
// samplers are stored in special uniforms
// So "ourTexture" is the sampler that we use to sample the texture we are using here
uniform sampler2D ourTexture;
uniform sampler2D ourTexture2;

void main() {
    // texture is a built-in function that takes a texture coordinate and sampler uniform and returns the color of the pixel at this coordinate
    // FragColor = texture(ourTexture, TexCoord);

    // OR

    // We can create our color mix from the vertex original color
    // FragColor = texture(ourTexture, TexCoord) * vec4(ourColor, 1.0);

    // OR 

    // We can mix textures
    FragColor = mix(texture(ourTexture, TexCoord), texture(ourTexture2, TexCoord), 0.2);
    // mix is a built-in function that takes two colors and a mix value and returns a new color
    // mix function works by interpolation
}